### ISSUE TITLE
About Auth?

### ISSUE THREAD

**Issue by b2r66sun** [akbaryahya/DockerGC#19]
Hi there, I'm confusing about things like authentication, because I found that everyone can login directly given the address, which is insecure to the server. So are there any configs to enable authentication?

**Comment by akbaryahya** [comment]
maybe after this is done https://github.com/Grasscutters/Grasscutter/pull/868 or via twitter

**Comment by KingRainbow44** [comment]
the server doesn't come with native auth, use a plugin like `GCAuth` instead

**Comment by b2r66sun** [comment]
got it, thanks
