### ISSUE TITLE
Add a command to use http

### ISSUE THREAD

**Issue by peerless-hero** [akbaryahya/DockerGC#21]
I want to use my own reverse proxy to provide SSL instead of the program's own SSL.
Please provide a command parameter to disable https and provide services using http protocol.
——————
我想用自己的反向代理程序提供SSL而不是程序自带的SSL。
请提供一个命令参数，禁用https，使用http协议提供服务。

**Comment by akbaryahya** [comment]
Sorry for late reply but this should be work by now https://github.com/akbaryahya/DockerGC/commit/da166895016128bb6a3495af05dea49ed5ac8ed7
