### ISSUE TITLE
Can't type in terminal and can't accesss server

### ISSUE THREAD

**Issue by Escartem** [akbaryahya/DockerGC#23]
I installed docker and mongodb, and created server using the commands for docker compose

But once it started I can't type anything in the terminal, so how do I type account create etc
I tried windows cmd, new windows terminal, git bash and docker cli but none works.

And also it says listening http://localhost:22102/ but this URL says connection refused when I open it.
Any help?

**Comment by akbaryahya** [comment]
try with 
`
docker attach dockergc
`
you can replace ***dockergc*** with the name container you are using, you can search with
`
docker ps
`
you can access the web server with 
`
https://localhost:443
`

**Comment by Escartem** [comment]
Ok thanks it works now but how do you login, or how do you install GCAuth plugin in the server?

**Comment by akbaryahya** [comment]
to login, please use the random password and username you are using
