### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ndzin** [akbaryahya/DockerGC#24]
I've done everything in the exact way that the tutorial says, but when I try to start the server it says:

Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening **socket**

![imagem_2022-06-08_013322948](https://user-images.githubusercontent.com/69260781/172532259-3b9a9d2e-e3ba-4728-8cbb-24074eeebc15.png)

What should I do?

**Comment by akbaryahya** [comment]
use `-d 'mongodb://useyourrealippcnotlocalhost:27017'`
