### ISSUE TITLE
Make docker compose and wrap it with mongodb

### ISSUE THREAD

**Issue by thatismunn** [akbaryahya/DockerGC#4]
*[Someone made the compose before but you can use it for reference](https://gist.github.com/suggoitanoshi/8aa4eccc0b1df4ca63a01beceb65546a), thanks to @suggoitanoshi for the gist.*

I see this server using Mongo as database. My suggestion to wrap it into compose because we don't need installing the mongodb out of the container. Just `docker compose up` and we're go.

**Comment by akbaryahya** [comment]
just made ^^
