### ISSUE TITLE
proxy seems broken?

### ISSUE THREAD

**Issue by xiazeyu** [akbaryahya/DockerGC#8]
It seems to support -p, but there's no code in current entry.sh

**Comment by akbaryahya** [comment]
yes currently only applies in version 2.8, I plan to create a separate proxy

**Comment by xiazeyu** [comment]
Yep, Mitmproxy currently has some dumb certification issue. 
From the document, This CA is used for on-the-fly generation of dummy certificates for each visited website. So every new Mitmproxy instance need users to click into http://mitm.it/ to download new certification.
However, the server itself needs restart sometimes. So it's better to seperate proxy.

**Comment by akbaryahya** [comment]
yes that's why I also put it in entrypoint.sh including install so that weight of the image doesn't add to it. because I haven't been successful with Mitmproxy so far I've only tested with Fiddler with the help of an MagiskTrustUserCerts that makes a user certification to root certification
