### ISSUE TITLE
Cloning into 'gi-bin-output'... remote: Repository unavailable due to DMCA takedown.

### ISSUE THREAD

**Issue by nEdAy** [akbaryahya/DockerGC#9]
Cloning into 'gi-bin-output'...
remote: Repository unavailable due to DMCA takedown.
remote: See the takedown notice for more details:
remote:   https://github.com/github/dmca/blob/master/2022/04/2022-04-28-genshin-impact.md.
fatal: unable to access 'https://github.com/radioegor146/gi-bin-output/': The requested URL returned error: 403

**Comment by akbaryahya** [comment]
old version for resources file has been taken down so try it "siakbary/dockergc:debian-dev-3.3"
